{'application': True,
 'author': 'Alderete Informatica (prototipo)',
 'category': 'Operations',
 'data': ['security/security.xml',
          'security/ir.model.access.csv',
          'views/menus.xml',
          'views/padron_mesa_views.xml',
          'views/padron_event_views.xml',
          'views/res_users_views.xml',
          'views/res_partner_views.xml',
          'views/fleet_vehicle_views.xml',
          'views/padron_checkin_views.xml',
          'views/padron_vehicle_control_views.xml',
          'views/padron_transport_views.xml',
          'views/padron_operacion_control_views.xml',
          'wizards/padron_quick_vote_wizard_views.xml',
          'wizards/padron_quick_transport_wizard_views.xml',
          'wizards/padron_vehicle_assign_wizard_views.xml'],
 'depends': ['base', 'contacts', 'fleet'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'Padrón Electoral - Control de Voto y Traslado',
 'summary': 'Carga masiva de padrón, control por Mesa, marcación de voto y control de traslado por vehículo.',
 'version': '18.0.1.0.3'}
