# -*- coding: utf-8 -*-
{
    'name': 'Sale Operational Flow',
    'version': '19.0.1.0.0',
    'summary': 'Flujo operativo: Vendedor → Caja → Despacho (backend puro, sin POS)',
    'category': 'Sales/Sales',
    'author': 'Your Company',
    'license': 'LGPL-3',
    'assets': {
        'web.assets_backend': [
            'sale_op_flow/static/src/css/sale_op_flow.css',
            'sale_op_flow/static/src/js/coupon_widget.js',
            'sale_op_flow/static/src/js/sof_print_wizard_auto.js',
            'sale_op_flow/static/src/js/branch_stock_button.js',
            'sale_op_flow/static/src/xml/branch_stock_button.xml',
        ],
    },
    'depends': ['sale_management', 'sale_stock', 'account', 'stock', 'mail', 'base_setup', 'partner_autocomplete', 'sale_order_line_pricelist', 'hr'],
    'post_init_hook': 'post_init_hook',
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'views/res_partner_views.xml',
        'views/sale_financing_plan_views.xml',
        'wizard/cashier_open_wizard_views.xml',
        'wizard/cashier_cash_move_wizard_views.xml',
        'views/sale_cashier_session_views.xml',
        'wizard/sof_product_branch_stock_wizard_views.xml',
        'views/sale_order_views.xml',
        'views/sale_order_line_product_search.xml',
        'views/sale_dispatch_stage_views.xml',
        'views/sale_cashier_board_views.xml',
        'views/sale_vendor_board_views.xml',
        'views/sale_op_flow_config_views.xml',
        'views/stock_picking_views.xml',
        'wizard/cashier_payment_wizard_views.xml',
        'wizard/cashier_close_wizard_views.xml',
        'wizard/quick_customer_wizard_views.xml',
        'wizard/dispatch_wizard_views.xml',
        'wizard/sof_print_wizard_views.xml',
        'wizard/sale_exchange_wizard_views.xml',
        'wizard/sof_supervisor_pin_wizard_views.xml',
        'views/sale_exchange_views.xml',
        'report/sale_order_report.xml',
        'report/report_cashier_session_views.xml',
        'report/sof_payment_report_views.xml',
        'report/sof_sale_report_views.xml',
        'report/sof_exchange_report_views.xml',
        'report/sof_session_report_views.xml',
        'report/sof_period_report_templates.xml',
        'wizard/sof_period_report_wizard_views.xml',
        'wizard/cashier_account_payment_wizard_views.xml',
        'views/menus.xml',
        'data/cron_data.xml',
        'data/dispatch_stage_data.xml',
        'data/cashier_stage_data.xml',
        'data/vendor_stage_data.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
